// chapters/ch10.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch10-data.js';

const section = document.getElementById('ch10');
mountChapter(section, cards);
