// chapters/ch11.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch11-data.js';

const section = document.getElementById('ch11');
mountChapter(section, cards);
