// chapters/ch12.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch12-data.js';

const section = document.getElementById('ch12');
mountChapter(section, cards);
