// chapters/ch13.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch13-data.js';

const section = document.getElementById('ch13');
mountChapter(section, cards);
