// chapters/ch6.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch6-data.js';

const section = document.getElementById('ch6');
mountChapter(section, cards);
