// chapters/ch7.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch7-data.js';

const section = document.getElementById('ch7');
mountChapter(section, cards);
