// chapters/ch9.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch9-data.js';

const section = document.getElementById('ch9');
mountChapter(section, cards);
