// chapters/ch15.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch15-data.js';

const section = document.getElementById('ch15');
mountChapter(section, cards);
