// chapters/ch16.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch16-data.js';

const section = document.getElementById('ch16');
mountChapter(section, cards);
