// chapters/ch17.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch17-data.js';

const section = document.getElementById('ch17');
mountChapter(section, cards);
