// chapters/ch18.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch18-data.js';

const section = document.getElementById('ch18');
mountChapter(section, cards);
