// chapters/ch21.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch21-data.js';

const section = document.getElementById('ch21');
mountChapter(section, cards);
