// chapters/ch4.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch4-data.js';

const section = document.getElementById('ch4');
mountChapter(section, cards);
