// chapters/ch5.js — auto-generated by build_chapters.py
// Triggered by main.js IntersectionObserver via import().
import { mountChapter } from './shared.js';
import { cards } from './ch5-data.js';

const section = document.getElementById('ch5');
mountChapter(section, cards);
